//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stubs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stubs.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {  
        ///   &quot;clients&quot;:[  
        ///      {  
        ///         &quot;id&quot;:&quot;a0ece5db-cd14-4f21-812f-966633e7be86&quot;,
        ///         &quot;name&quot;:&quot;Britney&quot;,
        ///         &quot;email&quot;:&quot;britneyblankenship@quotezart.com&quot;,
        ///         &quot;role&quot;:&quot;admin&quot;
        ///      },
        ///      {  
        ///         &quot;id&quot;:&quot;e8fd159b-57c4-4d36-9bd7-a59ca13057bb&quot;,
        ///         &quot;name&quot;:&quot;Manning&quot;,
        ///         &quot;email&quot;:&quot;manningblankenship@quotezart.com&quot;,
        ///         &quot;role&quot;:&quot;admin&quot;
        ///      },
        ///      {  
        ///         &quot;id&quot;:&quot;a3b8d425-2b60-4ad7-becc-bedf2ef860bd&quot;,
        ///         &quot;name&quot;:&quot;Barnett&quot;,
        ///         &quot;email&quot;:&quot;barnettblan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClientMockResult {
            get {
                return ResourceManager.GetString("ClientMockResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asdasd.
        /// </summary>
        internal static string PoliciesMockResult {
            get {
                return ResourceManager.GetString("PoliciesMockResult", resourceCulture);
            }
        }
    }
}
